### ISSUE TITLE
purefa_policy fails to create an export policy with specified nfs_version attribute

### ISSUE THREAD

**Issue by dbuenoparedes** [Pure-Storage-Ansible/FlashArray-Collection#682]
**Describe the bug**
When trying to create an NFS export policy using the purefa_policy module and specifying the nfs_version attribute the task fails. Without specifying the nfs_version (Purity defaults to v3) it works.

**To Reproduce**
1. Create a purefa_policy task specifying the nfs_version:
```
- name: Create NFS export policy
  purestorage.flasharray.purefa_policy:
    name: "{{ pol.name }}"
    policy: "{{ pol.type }}"
    client: "{{ pol.client | join(' ') }}"
    user_mapping: "{{ pol.user_mapping }}"
    nfs_version: "{{ pol.nfs_version | default(omit) }}"
    fa_url: "{{ fa_url }}"
    api_token: "{{ api_token }}"
```
2. Run playbook that includes previous task
3. See error
```
The full traceback is:
Traceback (most recent call last):
  File "master:/home/dbuenoparedes/git-repos/8x8/ansible-vcc/venv/lib/python3.10/site-packages/ansible_mitogen/runner.py", line 1039, in _run
    self._run_code(code, mod)
  File "master:/home/dbuenoparedes/git-repos/8x8/ansible-vcc/venv/lib/python3.10/site-packages/ansible_mitogen/runner.py", line 1003, in _run_code
    exec(code, vars(mod))
  File "master:/home/dbuenoparedes/git-repos/8x8/ansible-vcc/collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_policy.py", line 2105, in <module>
  File "master:/home/dbuenoparedes/git-repos/8x8/ansible-vcc/collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_policy.py", line 2097, in main
  File "master:/home/dbuenoparedes/git-repos/8x8/ansible-vcc/collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_policy.py", line 1134, in update_policy
TypeError: PolicyNfsPatch.__init__() got an unexpected keyword argument 'nfs_version'
failed: [pure01-p01] (item={'name': 'backups2_export_policy', 'type': 'nfs', 'user_mapping': False, 'client': ['192.168.130.0/24'], 'nfs_version': 'nfsv4'}) => changed=false 
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python3
  ansible_loop_var: pol
  module_stderr: |-
    Traceback (most recent call last):
      File "master:/home/dbuenoparedes/git-repos/8x8/ansible-vcc/venv/lib/python3.10/site-packages/ansible_mitogen/runner.py", line 1039, in _run
        self._run_code(code, mod)
      File "master:/home/dbuenoparedes/git-repos/8x8/ansible-vcc/venv/lib/python3.10/site-packages/ansible_mitogen/runner.py", line 1003, in _run_code
        exec(code, vars(mod))
      File "master:/home/dbuenoparedes/git-repos/8x8/ansible-vcc/collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_policy.py", line 2105, in <module>
      File "master:/home/dbuenoparedes/git-repos/8x8/ansible-vcc/collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_policy.py", line 2097, in main
      File "master:/home/dbuenoparedes/git-repos/8x8/ansible-vcc/collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_policy.py", line 1134, in update_policy
    TypeError: PolicyNfsPatch.__init__() got an unexpected keyword argument 'nfs_version'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  pol:
    client:
    - 192.168.130.0/24
    name: backups2_export_policy
    nfs_version: nfsv4
    type: nfs
    user_mapping: false
  rc: 1
```

**Expected behavior**
An export policy with the specified nfs version(s) should be created without any error.

**Desktop (please complete the following information):**
- OS: Linux Ubuntu 22.04
- ansible core 2.16.7
- purestorage.flasharray 1.32.0
- Pure flasharray model FA-X50R3, version 6.5.8

**Additional context**
Tried adding one or both nfs versions the following ways but none of them work:
- nfs_version: "nfsv4"
- nfs_version: "nfsv3", "nfsv4"

**Comment by dbuenoparedes** [comment]
Hi @sdodsley  you were right, I was inadvertently using `1.32.0`, I've just updated `py-pure-client` to `1.59.0` and rerun the task, it now works, thank you for pointing this out.

**Comment by dbuenoparedes** [comment]
Sorry @sdodsley, I said that too quickly, I was only running it in `--check` mode and that went through but when I actually run the task without --check mode it gives me the same error:
```
failed: [pure01-p01] (item={'name': 'blkupdate_export_policy', 'type': 'nfs', 'user_mapping': False, 'client': ['192.168.130.0/24'], 'nfs_version': 'nfsv4'}) => changed=false 
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python3
  ansible_loop_var: pol
  module_stderr: |-
    /home/dbuenoparedes/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.122.16.250'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
      warnings.warn(
    /home/dbuenoparedes/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.122.16.250'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
      warnings.warn(
    /home/dbuenoparedes/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.122.16.250'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
      warnings.warn(
    /home/dbuenoparedes/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.122.16.250'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
      warnings.warn(
    /home/dbuenoparedes/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.122.16.250'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
      warnings.warn(
    Traceback (most recent call last):
      File "master:/home/dbuenoparedes/git-repos/8x8/ansible-vcc/venv/lib/python3.10/site-packages/ansible_mitogen/runner.py", line 1039, in _run
        self._run_code(code, mod)
      File "master:/home/dbuenoparedes/git-repos/8x8/ansible-vcc/venv/lib/python3.10/site-packages/ansible_mitogen/runner.py", line 1003, in _run_code
        exec(code, vars(mod))
      File "master:/home/dbuenoparedes/git-repos/8x8/ansible-vcc/collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_policy.py", line 2105, in <module>
      File "master:/home/dbuenoparedes/git-repos/8x8/ansible-vcc/collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_policy.py", line 2097, in main
      File "master:/home/dbuenoparedes/git-repos/8x8/ansible-vcc/collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_policy.py", line 1134, in update_policy
    TypeError: PolicyNfsPatch.__init__() got an unexpected keyword argument 'nfs_version'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  pol:
    client:
    - 192.168.130.0/24
    name: blkupdate_export_policy
    nfs_version: nfsv4
    type: nfs
    user_mapping: false
  rc: 1
```

**Comment by sdodsley** [comment]
@dbuenoparedes can you post the response to this URL?
`https://<flasharray>/api/api_version`

**Comment by dbuenoparedes** [comment]
@sdodsley this is the response to that request:
```
```

**Comment by sdodsley** [comment]
@dbuenoparedes this should be working given you have the correct SDK installed. Can you double check the SDK version in the Ansible shell running the playbook? Might be worth adding a task to upgrade the SDK using pip at the start of the playbook

**Comment by dbuenoparedes** [comment]
@sdodsley sorry again, this was entirely my bad. I had a venv with `py-pure-client 1.59.0` **and** a global pip env with `py-pure-client 1.32.0` and for some reason it was using my _global_ pip instead of the venv one.

I've got my venv recreated with all packages and requirements and it's now working fine, I can confirm that `nfs_version` works with `py-pure-client 1.59.0`.

Thanks for checking anyway.
