### ISSUE TITLE
Client.get_hosts() got an unexpected keyword argument 'allow_errors

### ISSUE THREAD

**Issue by Aglidic** [Pure-Storage-Ansible/FlashArray-Collection#1016]
After upgrading collection to 1.43 we saw this error on the purefa_host module.

We had to rollback to 1.42 to make it works.

py-pure-client version: 1.89
purestorage: 1.19
ansible-core: 2.21.1
python: 3.12

**Comment by sdodsley** [comment]
@Aglidic you are correct - this error slipped in as `allow_errors` should have been gated on a REST version. Your arrays are obviosuly below that version, hence the crash.
We are fixing this now by adding the missing gate into the code and also the unit tests.
Expect a patch very soon.
